<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Tobey.Sprintaholic.SupermarketSimulator</AssemblyName>
    <Product>Sprintaholic</Product>
    <Version>1.3.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <DebugType>none</DebugType>
    <RootNamespace>Tobey.Sprintaholic.SupermarketSimulator</RootNamespace>
    <Configurations>Steam;GamePass</Configurations>
    <GamePath Condition="'$(Configuration)'=='Steam'">E:\SteamLibrary\steamapps\common\Supermarket Simulator</GamePath>
    <GamePath Condition="'$(Configuration)'=='GamePass'">E:\XboxGames\Supermarket Simulator\Content</GamePath>
  </PropertyGroup>

  <Target Name="ZipClean" AfterTargets="AfterClean">
    <Delete Files="$(SolutionDir)\bin\$(RootNamespace)_BepInEx5.zip;$(OutputPath)\zip\BepInEx\plugins\Tobey\$(Product)\$(TargetFileName)" />
  </Target>

  <Target Name="ZipBuild" AfterTargets="AfterBuild">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutputPath)\zip\BepInEx\plugins\" />
    <MakeDir Directories="$(SolutionDir)\bin" Condition="!Exists('$(SolutionDir)\bin')" />
    <ZipDirectory SourceDirectory="$(OutputPath)\zip\" DestinationFile="$(SolutionDir)\bin\$(RootNamespace).$(Configuration).zip" Overwrite="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="PolySharp" Version="1.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GamePath)\BepInEx\interop\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GamePath)\BepInEx\interop\Unity.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GamePath)\BepInEx\unity-libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GamePath)\BepInEx\unity-libs\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Import Project="..\Config\Config.projitems" Label="Shared" />
</Project>
